### ISSUE TITLE
Project Description Seite Videos einfügen

### ISSUE THREAD

**Issue by anmaht** [iGEM-Aachen/wiki2021#281]
Der Plan ist: ein neutrales Bild im Header, darunter das Video von dem iGEM Logo, was reinzoomt und dann unser Projekt kurz erklärt. Im Text unter Characteristics der TdT dann noch die Animation der TdT einfügen

**Comment by clemenskoehler** [comment]
Wenn wir ein Video einfügen was inhaltlich wichtig ist wird die Seite voll lange zum laden brauchen

**Comment by anmaht** [comment]
Ja, aber ist ja nicht unsere Startseite und Malte versucht, das zu kompremieren. Wir im Incubator sind dafür, dass es umgesetzt wird :):D

**Comment by Palaract** [comment]
Wenn mir jemand erklärt was für Videos wohin sollen, dann mache ich das gerne, insofern die Dateigröße der Videos nicht die unsichtbare Masse aus dem Incubator übersteigt.

**Comment by malteschwerin** [comment]
Das Video ist 3.7 MB groß, bei mir läuft es ganz gut
