### ISSUE TITLE
Einrückung Quellen ändern

### ISSUE THREAD

**Issue by kdotk1** [iGEM-Aachen/wiki2021#355]
Die Quellen sind sehr nach rechts eingerückt, was viel Platz wegenimmt. Kann man das nicht auf die gleiche Höhe wie den Text machen?

**Comment by Palaract** [comment]
Kannst du das genauer ausführen? Ich verstehe nicht ganz was gemeint ist.

**Comment by kdotk1** [comment]
![Quellen_einrücken](https://user-images.githubusercontent.com/87171537/137862579-62365d4c-cf19-487b-b0be-606a3b627767.png)
