### ISSUE TITLE
Change "Engineering" to "Engineering Success"

### ISSUE THREAD

**Issue by marielaufens** [iGEM-Aachen/wiki2021#401]
Ich fände es sinnvoll, wenn die Seite "Engineering" "Engineering Success" heißen würde, da man da eher versteht, was gemeint ist, glaube ich. Also zumindest, dass das im Header steht, ich weiß nicht, ob das nicht zu lang für die Menübar ist

**Comment by clemenskoehler** [comment]
Wurde gestern im Meeting ja besprochen und bestätigt :D
