### ISSUE TITLE
Sidebar Link zu lang auf Description page

### ISSUE THREAD

**Issue by Palaract** [iGEM-Aachen/wiki2021#422]
Auf der [Description Page](https://2021.igem.org/Team:Aachen/Description) ist der Abschnitt "Characteristics of the Terminal Deoxynucleotidyl Transferase" auf der Sidebar zu lang und geht aus der Sidebar raus.

**Comment by Tobias-J** [comment]
Der Vollständigkeit halber: im Notebook sind auch viele Überschriften zu lang für die Sidebar. Denke der Zeilenumbruch sollte einfach etwas früher erfolgen, dann müsste sich das ja für alle Seiten lösen.
