### ISSUE TITLE
Attributions Special Thanks to

### ISSUE THREAD

**Issue by Mart1nZens** [iGEM-Aachen/wiki2021#562]
Texteinrückung entfernen bei Luis Budow

**Comment by marielaufens** [comment]
Hab ich unwissentlich gefixt. Da war nicht die Einrückung falsch, sondern der Text war glaube ich zentriert, weil es nur eine Zeile war. Ich wollte eh noch einen Satz hinzufügen, also hat es sich jetzt von selbst gefixt :)
