### ISSUE TITLE
Fact of the week Bilder anklicken

### ISSUE THREAD

**Issue by kdotk1** [iGEM-Aachen/wiki2021#57]
Bei dem Eintrag zu fact of the week soll man die Bilder anklicken können, sodass sie größer (mit evtl. verschwommenem Hintergrund) erscheinen. Links und rechts sollen Pfeile sein, mit denen man sich im Post durchklicken kann.
![Idee fact of the week_Zeichenfläche 1](https://user-images.githubusercontent.com/87171537/135863980-14077225-3b00-4ff4-b495-950e0f463bf1.png)

**Comment by Mart1nZens** [comment]
@kdotk1 willst evtl. alle anderen Fact of the Weeks verlinken? Wäre schade wenn deine ganze Arbeit nicht auf dem Wiki ist
