### ISSUE TITLE
Startseite Text ändern

### ISSUE THREAD

**Issue by kdotk1** [iGEM-Aachen/wiki2021#667]
As in previous years, the Aachen iGEM team was again very successful. Bitte ändern zu:

As in previous years, the iGEM Team Aachen was very successful in the competition.

**Comment by marielaufens** [comment]
Dieses issue wollte ich auch gerade erstellen xD

**Comment by marielaufens** [comment]
Außerdem heißt es "prizes" und nicht "prices" glaube ich
